### ISSUE TITLE
Error while trying to run face_recorder.py

### ISSUE THREAD

**Issue by cluzier** [pranavmicro7/Emojinator#1]
Here is the output when I do `python3 face_recorder.py`

hope someone is able to lend a hand.

```[tcp @ 0x7fccebdfbf40] Connection to tcp://192.168.43.1:8080 failed: Operation timed out
OpenCV: Couldn't read video stream from file "http://192.168.43.1:8080/video"
Traceback (most recent call last):
  File "face_recorder.py", line 20, in <module>
    img=cv2.resize(img,(600,400))
cv2.error: OpenCV(4.1.0) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'resize'```

**Comment by pranavmicro7** [comment]
Instead of "cap=cv2.VideoCapture('http://192.168.43.1:8080/video')"

Try " 
cap=cv2.VideoCapture(0)"

I have used my mobile camera to record the face so if you are using your  default webcamera then replace the address with '0'.

**Comment by cluzier** [comment]
> Instead of "cap=cv2.VideoCapture('http://192.168.43.1:8080/video')"
> 
> Try "
> cap=cv2.VideoCapture(0)"
> 
> I have used my mobile camera to record the face so if you are using your default webcamera then replace the address with '0'.

thank you.
